# Generated by Django 5.1.1 on 2024-10-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_alter_users_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='full_name',
        ),
    ]
