# Generated by Django 5.1.1 on 2024-10-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0003_remove_users_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
