# Generated by Django 5.1.2 on 2024-10-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0004_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
