# Generated by Django 5.1.2 on 2024-10-17 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0005_alter_users_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
