# Generated by Django 5.1.2 on 2024-10-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0008_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
