# Generated by Django 5.1.2 on 2024-10-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0009_users_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='Profile pictures'),
            preserve_default=False,
        ),
    ]
