# Generated by Django 5.1.2 on 2024-10-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0010_users_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile_pic',
            new_name='ProfilePicture',
        ),
        migrations.RemoveField(
            model_name='users',
            name='profile_pic',
        ),
        migrations.AlterModelTable(
            name='profilepicture',
            table='profile_pic',
        ),
    ]
