# Generated by Django 5.1.2 on 2024-10-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0011_rename_profile_pic_profilepicture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
