# Generated by Django 5.1.2 on 2024-10-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0015_usertask'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usertask',
            table='todo',
        ),
    ]
